library('testthat')
library('ProjectTemplate')
create.project("dataanalysys-project1")
setwd("/home/fontanon/Dropbox/Devel/dataanalysis-project1/")
savehistory("~/Dropbox/Devel/dataanalysis-project1/dataanalysys-project1/src/history.R")
download.file("http://spark-public.s3.amazonaws.com/dataanalysis/loansData.csv", destfile="data/loansData.csv")
download.file("http://spark-public.s3.amazonaws.com/dataanalysis/loansData.rda", destfile="data/loansData.rda")
download.file("http://spark-public.s3.amazonaws.com/dataanalysis/loansCodebook.pdf", destfile="data/loansCodebook.pdf")
dateDownloaded <- date()
savehistory("~/Dropbox/Devel/dataanalysis-project1/dataanalysys-project1/src/history.R")
